#!/bin/bash
# set -x

if [ $# -lt 2 ]; then
  echo "usage: perf_run iterations options [conf-name]"
  echo "example: perf_run 100 \"o1 o2 o3\" pdata"
  exit 1
fi

BINDIR=`dirname $0`

test -z "$RAILS_PERF_DATA" && RAILS_PERF_DATA=$HOME

ITER="$1"
OPT="$2"
if [ $# == 3 ]; then
  DATE=`date +%m-%d`
  RAILS_BENCHMARK_FILE="$RAILS_PERF_DATA/$DATE.$3.txt"
else
  RAILS_BENCHMARK_FILE="$RAILS_PERF_DATA/perf_run.txt"
fi
export RAILS_BENCHMARK_FILE

PERF_OPTIONS="$ITER $OPT"
$BINDIR/perf_loop $PERF_OPTIONS

ruby $BINDIR/perf_times $RAILS_BENCHMARK_FILE
