#!/usr/bin/env ruby

bindir = File.dirname(__FILE__)
ENV['RAILS_PERF_RUNS'] ||= "3"

file=ENV['RAILS_BENCHMARK_FILE']
#if [ "$OSTYPE" == "cygwin" ]; then
#  RAILS_BENCHMARK_FILE=`cygpath -m $FILE`
#fi

ENV.delete 'RUBY_GC_STATS'

patched_gc="no"
ARGV.each{|arg| patched_gc=$1 if arg =~ /\A-gc=([^ ]*)\Z/}

if patched_gc == "no"
  %w(RUBY_HEAP_MIN_SLOTS RUBY_GC_MALLOC_LIMIT RUBY_HEAP_FREE_MIN).each{|v| ENV.delete v}
else
  File.open("#{ENV['RAILS_ROOT']}/config/#{patched_gc}.gc").each_line do |line|
    ENV[$1] = $2 if line =~ /^(.*)=(.*)$/
  end
end

null = (RUBY_PLATFORM =~ /win32/i) ? 'nul' : '/dev/null'
perfcmd = "ruby #{bindir}/perf_bench #{ARGV.join(' ')} >#{null}"
# puts perfcmd

puts "benchmarking #{ENV['RAILS_PERF_RUNS']} runs with options #{ARGV.join(' ')}"

File.open(file, "w"){ |f| f.puts "#{bindir}/perf_bench #{ARGV.join(' ')}" }

ENV['RAILS_PERF_RUNS'].to_i.times do
  system(perfcmd) || exit(1)
end

File.open(file, "a" ){|f| f.puts }

# puts "performance data written to file #{file}"
