#!/usr/bin/env ruby

if ARGV.length < 4
  $stderr.puts 'usage: perf_diff_gc iterations options1 options2 [conf-name1] [conf-name2]'
  $stderr.puts 'example: perf_diff_gc 100 "-bm=default" "-log" "-nocache" c1 c2'
  exit 1
end

bindir = File.dirname(__FILE__)
require "#{bindir}/../lib/railsbench/perf_utils"

perf_data_dir = (ENV['RAILS_PERF_DATA'] ||= ENV['HOME'])

iterations = ARGV[0]
common = ARGV[1]
options1 = ARGV[2]
options2 = ARGV[3]
date = Time.now.strftime '%m-%d'

benchmark = ""
benchmark = $1 if common =~ /-bm=([^ ]+)/

warmup = "-warmup"

if ARGV[4]
  file1 = "#{perf_data_dir}/#{date}.#{benchmark}.#{ARGV[4]}.gc.txt"
else
  file1 = "#{perf_data_dir}/perf_run1.#{benchmark}.gc.txt"
end
if ARGV[5]
  file2 = "#{perf_data_dir}/#{date}.#{benchmark}.#{ARGV[5]}.gc.txt"
else
  file2 = "#{perf_data_dir}/perf_run2.#{benchmark}.gc.txt"
end

null = (RUBY_PLATFORM =~ /win32/i) ? 'nul' : '/dev/null'

perf_options = "#{iterations} #{warmup} #{common} #{options1}"

puts "benchmarking GC performance with options #{perf_options}"
puts

set_gc_variables([common, options1])
enable_gc_stats(file1)
perf_cmd = "ruby #{bindir}/run_urls #{perf_options} >#{null}"
system(perf_cmd) || die("perf_diff_gc: #{perf_cmd} returned #{$?}")

unset_gc_variables
disable_gc_stats

system("ruby #{bindir}/perf_times_gc #{file1}")
puts;puts

perf_options = "#{iterations} #{warmup} #{common} #{options2}"

puts "benchmarking GC performance with options #{perf_options}"
puts

set_gc_variables([common, options2])
enable_gc_stats(file2)

perf_cmd = "ruby #{bindir}/run_urls #{perf_options} >#{null}"
system(perf_cmd) || die("perf_diff_gc: #{perf_cmd} returned #{$?}")

unset_gc_variables
disable_gc_stats

system("ruby #{bindir}/perf_times_gc #{file2}")
puts;puts

puts "benchmark comparison data"
puts

system("ruby #{bindir}/perf_comp_gc #{file1} #{file2}")

__END__

#  Copyright (C) 2005, 2006  Stefan Kaes
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
