#!/usr/bin/env ruby

if ARGV.length == 0 || ARGV.length > 3
  puts "usage: perf_run iterations options [conf-name]"
  puts "example: perf_run 100 \"-bm=default -log\" pdata"
  exit 1
end

bindir = File.dirname(__FILE__)
require "#{bindir}/../lib/railsbench/perf_utils"

perf_data_dir = (ENV['RAILS_PERF_DATA'] ||= ENV['HOME'])

benchmark = ""
benchmark = $1 if ARGV[1] =~ /-bm=([^ ]+)/

date = Time.now.strftime '%m-%d'

if ARGV.length == 3
  benchmark_file = "#{perf_data_dir}/#{date}.#{benchmark}.#{ARGV[2]}.txt"
else
  benchmark_file = "#{perf_data_dir}/perf_run.#{benchmark}.txt"
end

ENV['RAILS_BENCHMARK_FILE'] = benchmark_file
perf_loop(ARGV)
unset_gc_variables
system("ruby #{bindir}/perf_times #{benchmark_file}")

__END__

#  Copyright (C) 2005, 2006  Stefan Kaes
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
