#!/bin/sh
# set -x

BINDIR=`dirname $0`
test -z $RAILS_PERF_RUNS && RAILS_PERF_RUNS=3

FILE=$RAILS_BENCHMARK_FILE
if [ "$OSTYPE" == "cygwin" ]; then
  RAILS_BENCHMARK_FILE=`cygpath -m $FILE`
fi

unset RUBY_GC_STATS

echo "benchmarking $RAILS_PERF_RUNS runs with options $@"
echo "$BINDIR/perf_bench $@" >$FILE

patched_gc="no"
for arg in $@; do
  case $arg in
   -gc=*) patched_gc=${arg#-gc=};;
  esac
done

if [ "${patched_gc}" = "no" ]; then
  unset RUBY_HEAP_MIN_SLOTS RUBY_GC_MALLOC_LIMIT RUBY_HEAP_FREE_MIN
else
  . $RAILS_ROOT/config/${patched_gc}.gc
  export RUBY_HEAP_MIN_SLOTS RUBY_GC_MALLOC_LIMIT RUBY_HEAP_FREE_MIN
fi

i=$(( $RAILS_PERF_RUNS ))
while [ $i -gt 0 ]; do
  i=$(( $i-1 ))
  ruby $BINDIR/perf_bench $@ >/dev/null || exit 1
done
echo >>$FILE

# echo "performance data written to file $RAILS_BENCHMARK_FILE"
