#!/usr/bin/env ruby

require 'rubygems'
require 'gruff'

$:.unshift(File.expand_path(File.dirname(__FILE__) + '/../lib'))
require 'railsbench/gc_info'

# extract options

selection = []
title = "GC Data Plot"
files = []
names = []
labels = %w()
perf_data = []
graph_type = Gruff::StackedBar
graph_width = '1400x1050'
font_size = 10
ignored_object_types = %w(NODE STRING)
output_file = "graph.png"
plot_live = true
plot_freed = true

ARGV.each do |arg|
  case arg
  when /^-width=(\d+)$/
    graph_width = $1.to_i
  when /^-geometry=(\d+x\d+)$/
    graph_width = $1
   when /^-title=(.*)$/
     title = $1 unless $1.strip.empty?
#   when /^-names=(.+)$/
#     names = $1.split(',')
  when /^-font_size=(\d+)$/
    font_size = $1.to_i
  when /^-ignore=(.*)$/
    ignored_object_types = $1.split(',').compact.map{|s|s.upcase}
  when /^-out=(.+)$/
    output_file = $1
  when /^-type=(.+)$/
    plot_freed = plot_live = false
    $1.split(/,/).compact.each do |plot_what|
      case plot_what
      when 'live' then plot_live = true
      when 'freed' then plot_freed = true
      else
        die "unknown plot type: #{$1}"
      end
    end
  else
    files << File.open_or_die(arg)
    names[files.length-1] ||= File.basename(arg)
  end
end

files.length > 0 or die "usage: perf_plot_gc [options] file1 file2 ..."

object_types = %w(NODE STRING ARRAY HASH  SCOPE VARMAP CLASS ICLASS REGEXP FLOAT MATCH FILE DATA MODULE OBJECT)

gcis = []
files.each do |file|
  gcis << GCInfo.new(file)
  file.close
end

object_types = GCInfo.object_types(gcis)
gc_count_max = gcis.map{|gci| gci.collections}.max
gc_max_processed = gcis.map{|gci| gci.processed_max}.max
gc_max_freed = gcis.map{|gci| gci.freed_max}.max
gc_max_live = gcis.map{|gci| gci.live_max}.max

g = graph_type.new(graph_width)

# on OS X, ImagMagick can't find it's default font (arial) sometimes, so specify some font
# g.font = 'Arial-Normal' if RUBY_PLATFORM =~ /darwin/
g.font = 'Helvetica-Narrow' if RUBY_PLATFORM =~ /darwin/

%w(#FF0000 #00FF00 #0000FF #D2FF77 #FF68C0 #D1FDFF #FFF0BD #15FFDC
).each do |color|
 g.add_color(color)
end

g.title = title + " ["
g.title += "freed" if plot_freed
g.title += "," if plot_freed && plot_live
g.title += "live" if plot_live
g.title += "]"
g.title += " (ignoring #{ignored_object_types.join(', ')})" unless ignored_object_types.empty?
g.sort = false
g.title_font_size = font_size+2
g.legend_font_size = font_size-2
g.legend_box_size = font_size-2
g.marker_font_size = font_size-2
if ignored_object_types.empty?
  g.minimum_value = 0
  maximums = []
  maximums << gc_max_live if plot_live
  maximums << gc_max_freed if plot_freed
  g.maximum_value = maximums.max
end
label_step = 0
label_step += 1 if plot_live
label_step += 1 if plot_freed
g.labels = Hash[* (0...gc_count_max).map{|i| [label_step*i*files.length, i.to_s]}.flatten ]
# puts g.labels.inspect
# puts object_types.inspect
puts "ignoring #{ignored_object_types.join(', ')}" unless ignored_object_types.empty?

object_types.each do |ot|
  next if ignored_object_types.include?(ot)
  data = []
  gc_count_max.times do |gc_index|
    for gci in gcis
      map_at_this_gc = gci.freed_objects[gc_index]
      data << ((map_at_this_gc && map_at_this_gc[ot]) || 0) if plot_freed
      map_at_this_gc = gci.live_objects[gc_index]
      data << ((map_at_this_gc && map_at_this_gc[ot]) || 0) if plot_live
    end
  end
  # puts "#{ot}: #{data.inspect}"
  g.data(ot, data)
end

class Gruff::StackedBar < Gruff::Base
  alias_method :old_draw, :draw
  def draw
    @d = @d.stroke_antialias false
    old_draw
  end
end

g.write(output_file)


__END__

#    Copyright (C) 2005-2008  Stefan Kaes
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
